version: "3"

volumes:
  prowlarr_config:
    name: prowlarr_config
    external: true
  radarr_config:
    name: radarr_config
    external: true
  transmission_config:
    name: transmission_config
    external: true
  jellyseerr_config:
    name: jellyseerr_config
    external: true

services:
  jellyseerr: # https://hub.docker.com/r/fallenbagel/jellyseerr
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    ports:
      - 5055:5055
    environment:
      - TZ=${TZ}
      - LOG_LEVEL=warning
    volumes:
      - jellyseerr_config:/app/config
    networks:
      - pirate
    restart: unless-stopped


  transmission: # https://hub.docker.com/r/linuxserver/transmission
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - TRANSMISSION_WEB_HOME= #optional
      - USER= #optional
      - PASS= #optional
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    volumes:
      - transmission_config:/config
      - ./downloads:/downloads
      - ./torrents:/watch
    networks:
      - pirate
    restart: unless-stopped

  radarr: # https://github.com/linuxserver/docker-radarr
    image: linuxserver/radarr:latest
    container_name: radarr
    ports:
      - 7878:7878
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - radarr_config:/config
      - /home/hakon/Movies:/movies
      - ./downloads:/downloads
    networks:
      - pirate
    restart: unless-stopped

  prowlarr: # https://github.com/linuxserver/docker-prowlarr
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    ports:
      - 9696:9696
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - prowlarr_config:/config
      - ./torrents:/downloads  # transmission watch directory
    networks:
      - pirate
    restart: unless-stopped

networks:
  pirate:
    name: pirate
